version: '3'

services:
  producer:
    build: .
    # image: node:16
    command: node example_scripts/producer.js example_scripts/getting-started.properties
    volumes:
      - .:/app
    # sysctls:
    #   - net.ipv4.tcp_keepalive_time=200
    #   - net.ipv4.tcp_keepalive_intvl=200
    #   - net.ipv4.tcp_keepalive_probes=5